Create README
Terasology/WorldPortals pull request #1
Opened 2018-01-05 02:58 UTC by MaxBorsch

2018-01-05 04:04 UTC, vampcat requested changes
Apart from the comments, I would like to see a `Getting Started` or `How to use this Module` section, *aimed at players*. Assume I just downloaded Terasology off the internet and downloaded this module, how do I spawn my own portals and play around with them? (if it's not possible, then mentioned it as such - `This module is aimed as a depency for other modules, and cannot be used directly by the player` or something)

2018-01-05 04:04 UTC, vampcat commented on README.md
> +A module to add teleportation portals. Portals currently occupy a block and transport any entities that enter the occupied block to the portals destination world position.
"A module to add teleportation portals."
This feels.. abrupt. Rephrasing it to "This module adds ..." makes it feel more natural.

"... to the portals destination ..."
You missed an apostrophe here. (Not trying to be a grammar nazi, the lack of apostrophe changes the meaning, throwing off the reader)

2018-01-05 04:04 UTC, vampcat commented on README.md
> +## Future Features
Unless there is good reason, I would push this down to the very end.
(keep in mind that these are ToDos, that may or may not ever get implemented. This readme is for the players as much as is it for the developers, and both of them are concerned primarily with what the module *currently* offers, not what it *might* offer some day)

2018-01-05 04:04 UTC, vampcat commented on README.md
> +## PortalComponent
Make this a subheading, and shift it down into a `Implementation` heading.

2018-01-05 04:04 UTC, vampcat commented on README.md
> +## PortalRasterizer & related.
"PortalRasterizer & related."
Change the & to and. Further, and remove the period at the end of the heading. Further, "& related." : related what? It ends way too abruptly.
Note that this heading should also become a subheading under `Implementation`.

2018-01-05 04:04 UTC, vampcat commented on README.md
> +An abstract class that generates rectangular portal structures in the world, to be implemented in modules that need quick portals in the world or as a usage demo.
I don't see any reference to any sort of "related" stuff here.

`or as a usage demo`
That is not something you explicitly need to mention.

2018-01-05 04:04 UTC, vampcat commented on README.md
> +An example portal structure used in Underworld module:
Make a separate heading for this : `Sample Implementation` or `Module Usage` or whatever suits your fancy.

2018-01-05 18:12 UTC, MaxBorsch commented
@vampcat Fixed and resubmitted.

2018-01-05 18:31 UTC, vampcat approved these changes
I'm satisfied with it.

2020-04-07 21:18 UTC, casals commented
Merging as per conversation history/current README version

2020-04-07 21:18 UTC, merged